repos:
  - repo: https://github.com/returntocorp/semgrep # HTTPS
    rev: "v0.85.0"
    hooks:
      - id: semgrep
        name: Semgrep Python
        types: [python]
        exclude: "^semgrep/tests/.+$|^scripts/.+$|^semgrep/setup.py$"
        args: ["--config", "https://semgrep.dev/p/python", "--error"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^semgrep\/tests\/.+$|^perf\/bench\/gitlab-rules\/.+$$
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: fix-byte-order-marker